### ISSUE TITLE
Organizar as fotos em pasta

### ISSUE THREAD

**Issue by Israel-Carneiro** [cts93/csv-meu-rio#1]
Oi Carlos 👋 sou seu colega da turma 20!

Então acabo de ver o seu repositório csv-meu-rio, e percebi que há apenas 3 paginas html e 4 css (eu acho rs). Mas fica difícil identificar elas com tantas fotos juntas. Então gostaria de te sugerir que junte as fotos dentro de uma pasta "fotos" (por exemplo).

E sempre que você quiser apresentar elas nas paginas pela Tag <img> é só você adicionar "./fotos/" antes do nome da foto. Assim p programa entende o caminho q deve fazer até a foto. 
Exemplo: <img scr="./fotos/nome-da-foto.jpg">

Mas atenção! Se houver alguma letra maiúscula no nome da pasta, você tem que escrever exatamente como está no comando scr
Qualquer duvida fique a vontade pra me pedir ajuda. 😉👍

**Comment by cts93** [comment]
Fala, @Israel-Carneiro ! Bom te ver por aqui.

Incluí as imagens numa pasta separada e corrigi seus endereços. Sobre os 4 arquivos css: É porque um deles é o reset.css, que faz o papel de anular as configurações de layout nativas do navegador pra que não haja discrepâncias de design.

Obrigado pela contribuição.
